[package]
name = "test"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio = { version = "1.53.1", features = ["full"] }
finviz_sdk = { path = "../finviz_sdk" }
benzinga_sdk = { path = "../benzinga_sdk" }
alpaca_sdk = { path = "../alpaca_sdk" }
chrono.workspace = true
anyhow.workspace = true
dotenvy = "0.15"
futures = "0.3"
